version: '3.8'
services:
  analytics:
    image: ${LABEL}-analytics
    build:
      context: ../
      dockerfile: ./dockerfiles/analytics/Dockerfile-analytics
  api:
    image: ${LABEL}-api
    build:
      context: ../
      dockerfile: ./dockerfiles/api/Dockerfile-api
  client:
    image: ${LABEL}-client
    build:
      context: ../
      dockerfile: ./dockerfiles/client/Dockerfile-client
      args:
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_PORT: $MYSQL_PORT
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
  instanceserver:
    image: ${LABEL}-instanceserver
    build:
      context: ..
      dockerfile: ./dockerfiles/instanceserver/Dockerfile-instanceserver
  testbot:
    image: ${LABEL}-testbot
    build:
      context: ../
      dockerfile: ./dockerfiles/testbot/Dockerfile-testbot
